#############################################################################
# Makefile for building: Qt-notepad-exe
# Generated by qmake (2.01a) (Qt 4.8.5) on: sáb feb 8 17:40:24 2014
# Project:  Qt-notepad/Qt-notepad.pro
# Template: app
# Command: /usr/bin/qmake -spec /usr/lib/qt/mkspecs/linux-g++ CONFIG+=debug CONFIG+=declarative_debug -o Makefile Qt-notepad/Qt-notepad.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/lib/qt/mkspecs/linux-g++ -IQt-notepad -I/usr/lib/qt/include/QtCore -I/usr/lib/qt/include/QtGui -I/usr/lib/qt/include -I. -IQt-notepad -I.
LINK          = g++
LFLAGS        = -Wl,-rpath,/usr/lib/qt/lib
LIBS          = $(SUBLIBS)  -L/usr/lib/qt/lib -lQtGui -L/usr/lib/qt/lib -L/usr/X11R6/lib -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = Qt-notepad/main.cpp \
		Qt-notepad/notepadwindow.cpp moc_notepadwindow.cpp \
		qrc_recursos.cpp
OBJECTS       = main.o \
		notepadwindow.o \
		moc_notepadwindow.o \
		qrc_recursos.o
DIST          = /usr/lib/qt/mkspecs/common/unix.conf \
		/usr/lib/qt/mkspecs/common/linux.conf \
		/usr/lib/qt/mkspecs/common/gcc-base.conf \
		/usr/lib/qt/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/qt/mkspecs/common/g++-base.conf \
		/usr/lib/qt/mkspecs/common/g++-unix.conf \
		/usr/lib/qt/mkspecs/qconfig.pri \
		/usr/lib/qt/mkspecs/modules/qt_phonon.pri \
		/usr/lib/qt/mkspecs/modules/qt_webkit_version.pri \
		/usr/lib/qt/mkspecs/features/qt_functions.prf \
		/usr/lib/qt/mkspecs/features/qt_config.prf \
		/usr/lib/qt/mkspecs/features/exclusive_builds.prf \
		/usr/lib/qt/mkspecs/features/default_pre.prf \
		/usr/lib/qt/mkspecs/features/debug.prf \
		/usr/lib/qt/mkspecs/features/default_post.prf \
		/usr/lib/qt/mkspecs/features/declarative_debug.prf \
		/usr/lib/qt/mkspecs/features/shared.prf \
		/usr/lib/qt/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/lib/qt/mkspecs/features/warn_on.prf \
		/usr/lib/qt/mkspecs/features/qt.prf \
		/usr/lib/qt/mkspecs/features/unix/thread.prf \
		/usr/lib/qt/mkspecs/features/moc.prf \
		/usr/lib/qt/mkspecs/features/resources.prf \
		/usr/lib/qt/mkspecs/features/uic.prf \
		/usr/lib/qt/mkspecs/features/yacc.prf \
		/usr/lib/qt/mkspecs/features/lex.prf \
		/usr/lib/qt/mkspecs/features/include_source_dir.prf \
		Qt-notepad/Qt-notepad.pro
QMAKE_TARGET  = Qt-notepad-exe
DESTDIR       = 
TARGET        = Qt-notepad-exe

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)
	{ test -n "$(DESTDIR)" && DESTDIR="$(DESTDIR)" || DESTDIR=.; } && test $$(gdb --version | sed -e 's,[^0-9]\+\([0-9]\)\.\([0-9]\).*,\1\2,;q') -gt 72 && gdb --nx --batch --quiet -ex 'set confirm off' -ex "save gdb-index $$DESTDIR" -ex quit '$(TARGET)' && test -f $(TARGET).gdb-index && objcopy --add-section '.gdb_index=$(TARGET).gdb-index' --set-section-flags '.gdb_index=readonly' '$(TARGET)' '$(TARGET)' && rm -f $(TARGET).gdb-index || true

Makefile: Qt-notepad/Qt-notepad.pro  /usr/lib/qt/mkspecs/linux-g++/qmake.conf /usr/lib/qt/mkspecs/common/unix.conf \
		/usr/lib/qt/mkspecs/common/linux.conf \
		/usr/lib/qt/mkspecs/common/gcc-base.conf \
		/usr/lib/qt/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/qt/mkspecs/common/g++-base.conf \
		/usr/lib/qt/mkspecs/common/g++-unix.conf \
		/usr/lib/qt/mkspecs/qconfig.pri \
		/usr/lib/qt/mkspecs/modules/qt_phonon.pri \
		/usr/lib/qt/mkspecs/modules/qt_webkit_version.pri \
		/usr/lib/qt/mkspecs/features/qt_functions.prf \
		/usr/lib/qt/mkspecs/features/qt_config.prf \
		/usr/lib/qt/mkspecs/features/exclusive_builds.prf \
		/usr/lib/qt/mkspecs/features/default_pre.prf \
		/usr/lib/qt/mkspecs/features/debug.prf \
		/usr/lib/qt/mkspecs/features/default_post.prf \
		/usr/lib/qt/mkspecs/features/declarative_debug.prf \
		/usr/lib/qt/mkspecs/features/shared.prf \
		/usr/lib/qt/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/lib/qt/mkspecs/features/warn_on.prf \
		/usr/lib/qt/mkspecs/features/qt.prf \
		/usr/lib/qt/mkspecs/features/unix/thread.prf \
		/usr/lib/qt/mkspecs/features/moc.prf \
		/usr/lib/qt/mkspecs/features/resources.prf \
		/usr/lib/qt/mkspecs/features/uic.prf \
		/usr/lib/qt/mkspecs/features/yacc.prf \
		/usr/lib/qt/mkspecs/features/lex.prf \
		/usr/lib/qt/mkspecs/features/include_source_dir.prf \
		/usr/lib/qt/lib/libQtGui.prl \
		/usr/lib/qt/lib/libQtCore.prl
	$(QMAKE) -spec /usr/lib/qt/mkspecs/linux-g++ CONFIG+=debug CONFIG+=declarative_debug -o Makefile Qt-notepad/Qt-notepad.pro
/usr/lib/qt/mkspecs/common/unix.conf:
/usr/lib/qt/mkspecs/common/linux.conf:
/usr/lib/qt/mkspecs/common/gcc-base.conf:
/usr/lib/qt/mkspecs/common/gcc-base-unix.conf:
/usr/lib/qt/mkspecs/common/g++-base.conf:
/usr/lib/qt/mkspecs/common/g++-unix.conf:
/usr/lib/qt/mkspecs/qconfig.pri:
/usr/lib/qt/mkspecs/modules/qt_phonon.pri:
/usr/lib/qt/mkspecs/modules/qt_webkit_version.pri:
/usr/lib/qt/mkspecs/features/qt_functions.prf:
/usr/lib/qt/mkspecs/features/qt_config.prf:
/usr/lib/qt/mkspecs/features/exclusive_builds.prf:
/usr/lib/qt/mkspecs/features/default_pre.prf:
/usr/lib/qt/mkspecs/features/debug.prf:
/usr/lib/qt/mkspecs/features/default_post.prf:
/usr/lib/qt/mkspecs/features/declarative_debug.prf:
/usr/lib/qt/mkspecs/features/shared.prf:
/usr/lib/qt/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/lib/qt/mkspecs/features/warn_on.prf:
/usr/lib/qt/mkspecs/features/qt.prf:
/usr/lib/qt/mkspecs/features/unix/thread.prf:
/usr/lib/qt/mkspecs/features/moc.prf:
/usr/lib/qt/mkspecs/features/resources.prf:
/usr/lib/qt/mkspecs/features/uic.prf:
/usr/lib/qt/mkspecs/features/yacc.prf:
/usr/lib/qt/mkspecs/features/lex.prf:
/usr/lib/qt/mkspecs/features/include_source_dir.prf:
/usr/lib/qt/lib/libQtGui.prl:
/usr/lib/qt/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/lib/qt/mkspecs/linux-g++ CONFIG+=debug CONFIG+=declarative_debug -o Makefile Qt-notepad/Qt-notepad.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/Qt-notepad-exe1.0.0 || $(MKDIR) .tmp/Qt-notepad-exe1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/Qt-notepad-exe1.0.0/ && $(COPY_FILE) --parents Qt-notepad/notepadwindow.h .tmp/Qt-notepad-exe1.0.0/ && $(COPY_FILE) --parents Qt-notepad/recursos.qrc .tmp/Qt-notepad-exe1.0.0/ && $(COPY_FILE) --parents Qt-notepad/main.cpp Qt-notepad/notepadwindow.cpp .tmp/Qt-notepad-exe1.0.0/ && (cd `dirname .tmp/Qt-notepad-exe1.0.0` && $(TAR) Qt-notepad-exe1.0.0.tar Qt-notepad-exe1.0.0 && $(COMPRESS) Qt-notepad-exe1.0.0.tar) && $(MOVE) `dirname .tmp/Qt-notepad-exe1.0.0`/Qt-notepad-exe1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/Qt-notepad-exe1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_notepadwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_notepadwindow.cpp
moc_notepadwindow.cpp: Qt-notepad/notepadwindow.h
	/usr/lib/qt/bin/moc $(DEFINES) $(INCPATH) Qt-notepad/notepadwindow.h -o moc_notepadwindow.cpp

compiler_rcc_make_all: qrc_recursos.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_recursos.cpp
qrc_recursos.cpp: Qt-notepad/recursos.qrc
	/usr/lib/qt/bin/rcc -name recursos Qt-notepad/recursos.qrc -o qrc_recursos.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean 

####### Compile

main.o: Qt-notepad/main.cpp Qt-notepad/notepadwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o Qt-notepad/main.cpp

notepadwindow.o: Qt-notepad/notepadwindow.cpp Qt-notepad/notepadwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o notepadwindow.o Qt-notepad/notepadwindow.cpp

moc_notepadwindow.o: moc_notepadwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_notepadwindow.o moc_notepadwindow.cpp

qrc_recursos.o: qrc_recursos.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_recursos.o qrc_recursos.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

